# Replace all occurrences of "INTERFACE" with the interface name (e.g. `HTTPCLIENT`)
# Replace all occurrences of "interface" with the folder name of the interface (e.g. `nats`, `httpclient`, etc)
name: INTERFACE

on:
  push:
    branches: [ main ]
    paths:
    - "interface/**"
  pull_request:
    branches: [ main ]
    paths:
    - "interface/**"

env:
  CARGO_TERM_COLOR: always
  working-directory: ./interface

jobs:
  rust_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: rust-check-action
      uses: wasmcloud/common-actions/rust-check@main
      with:
        working-directory: ${{ env.working-directory }}
